#!/usr/bin/env bash
# This script accepts a string as an argument and
#      Displays Usage: 5-is_the_host_on_the_network 
#               {IP_ADDRESS} if no argument passed.
#      Pings an IP address received as a string
#            argument 5 times.
# Author Bereket Dereje Mekkonen

if [ "$#" -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
