#!/usr/bin/env bash
# This script is displaying a list of 
#      currently running processes.
# It Shows all processes, for all users,
#    including those which might not have a TTY.
# Author Bereket Dereje

ps -auxf
