#!/usr/bin/env bash
# This script Does the following:
#      It Create a file /var/run/myscript.pid
#         containing the script PID.
#      It Displays "To infinity and beyond"
#         indefinitely
#      It Displays "I hate the kill command"
#         upon receiving a SIGTERM signal
#      It Displays "Y U no love me?!"
#         upon receiving a SIGINT  signal
#      It Deletes the file /var/run/myscript.pid
#         and terminates itself upon receiving 
#+        a SIGQUIT or SIGTERM signal.
# Author Bereket Dereje Mekkonen

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUITgit 
done
