#!/usr/bin/env bash
# This script displays "To infinity and beyond"
#      indefinitely with a sleep 2 (two) in
#      between each iteration.
# It Displays "I am invincible!!!"
#    in between each iteration.
# Author Bereket Dereje Mekonnen

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
