#!/usr/bin/env bash
# This script displays all active IPv4 addresses
#      IPs on the machine it’s executed on.
# Author Bereket Dereje Mekkonen

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
