#!/usr/bin/env bash
# Bash script that Creates SSH-RSA key pair
#    Name of the created private key must be school
#    Number of bits in the created key to be created 4096
#    The created key must be protected by the passphrase betty
# Author Bereket Dereje

ssh-keygen -b 4096 -f school -t rsa -N betty
